### PR TITLE
Pkg

### PR DESCRIPTION
**Pull request by fepitre**

### CODE REVIEW

**Comment by fepitre** [comment]
@marmarek, @sine3o14nnae: here is the packaging with slight modifications. Notably I enabled travis and add a specific job for ShellCheck. I fixed `qmenu-al` but others need refactor. I saw several commits on top of your master @sine3o14nnae. When this branch merged, do you mind to open PR of your modifications?

**Comment by fepitre** [comment]
@sine3o14nnae: another remark, please don't hard-code version in scripts. I don't see an easy way to maintain such information into help sentence.

**Comment by 3o14r473** [comment]
Thank you for the packaging.

I would love to open a PR. There are several improvements, like `qmenu-al` being able to also launch dom0 applications.

Regarding my commits, the file `qmenu.conf` is now obsolete. Adjusting qube label colors is now done by passing them as arguments to the script, using numbered shell variables (See the readme in [master](https://github.com/sine3o14nnae/qmenu)). This may look convoluted at first but i would strongly argue that configuring this in a seperate file is redundant. Most users will probably execute qmenu tools via shortcuts, so instead of creating a seperate file for this, the user can simply adjust the colors in the same file where they configure the shortcuts. Of course, i am open for any critique.

Understood, i will stop hard-coding versions.

**Comment by fepitre** [comment]
> Thank you for the packaging.
> 
> I would love to open a PR. There are several improvements, like `qmenu-al` being able to also launch dom0 applications.

Please PR on top of current master branch.

> 
> Regarding my commits, the file `qmenu.conf` is now obsolete. Adjusting qube label colors is now done by passing them as arguments to the script, using numbered shell variables (See the readme in [master](https://github.com/sine3o14nnae/qmenu)). This may look convoluted at first but i would strongly argue that configuring this in a seperate file is redundant. Most users will probably execute qmenu tools via shortcuts, so instead of creating a seperate file for this, the user can simply adjust the colors in the same file where they configure the shortcuts. Of course, i am open for any critique.

It's good to have a default configuration file for those who don't need specific changes. That's why I handled in `qmenu-al` the possibility of having `user wide` and `system wide` configuration files. User's one is prior to system one.

> 
> Understood, i will stop hard-coding versions.

**Comment by 3o14r473** [comment]
> It's good to have a default configuration file for those who don't need specific changes. That's why I handled in qmenu-al the possibility of having user wide and system wide configuration files. User's one is prior to system one.

But wouldn't those who do not need specific changes simply launch qmenu tools without any configuration? Both would result in a default qmenu.

**Comment by fepitre** [comment]
> But wouldn't those who do not need specific changes simply launch qmenu tools without any configuration? Both would result in a default qmenu.

Correct me if I'm wrong but the coloring is done only if colors are provided by qemu.conf right? If it's well the case, there is several solutions to having default nice feature you specifically provide in your tools and more than just default `dmenu`. One solution is to keep default conf file, which allows to add other type of options like `--light-theme`. Another solution is to hardcode default color values into your tools.

**Comment by 3o14r473** [comment]
No but you probably came to that conclusion because of my horrible description back then. If qmenu.conf is not provided, `qmenu` will pass 'red', 'blue', etc. as a string to `dmenu`. This results in eye-straining colors on most systems. If a user wanted to adjust _one_ label color, they had to adjust  _all_ 8. This is probably where my description confused you.

The latest version however, will simply use black and white (or w&b if light-theme is set) by default. Further, it will not crash if a user decides to adjust only a particular label color.

**Pull request merged**
