### PR TITLE
Update

### PR DESCRIPTION
**Pull request by 3o14r473**

### CODE REVIEW

**Comment by fepitre** [comment]
Please rebase your 'master' branch onto current 'master branch. At least, what you can do when working in such configuration, keep your master branch synchronized with Qubes one and create a separate branch for new features/updates and PR this new branch. For example, in this current PR, it does not take into account the modifications made previously like adding Travis-CI.

**Comment by 3o14r473** [comment]
Excuse me, i am new to this.

I hope that this solves the problem. If not, i may need some advice from you. Sorry

**Comment by fepitre** [comment]
I was about to write somthing and found this: https://gist.github.com/Chaser324/ce0505fbed06b947d962

Before you need to:
1) In your case you need to backup your current 'master' branch into another one like 'devel'. For that simply do in your current repository folder with master branch: `git checkout -b devel`. Then push to github your branch (for remote backup too).

2) Resync your master branch with the Qubes one. From the above gist, it's called `upstream`. So in your current repo folder you are on `devel` branch. Switch back to your `master` branch: `git checkout master`. Then you need to do a `git reset --hard upstream/master`. Please be aware that will destroy your current master branch. That's why you needed to create a backup branch here called `devel`.

3) From this refreshed/synced master branch with respect to Qubes one, you can either:
3.1) create a branch from `master` one called e.g. `improvements1` and then pick up commit from you backup `devel branch`. Please note that the way you added the three commits I made is wrong. Those would be here now because your master branch (and then your new branch `improvements1` is synced with the Qubes one).
3.2) create a branch from `devel` one called e.g. `improvements1` and do a `git rebase -i upstream/master`. Here you need to first drop the three commits you added from me and then you will have to fix certainly conflicts...

Also for features, default behavior etc I would suggest you to propose thoses into current issues '[Contribution]' related to your repository. In this way, we are not alone to handle those.

**Comment by 3o14r473** [comment]
Thank you very much for your thorough instructions. I hope i did not break anything.

**Comment by 3o14r473** [comment]
Regarding my last commit, I hope that it is not a problem to rename tools aslong as they have not been "shipped" to users yet. Please let me know otherwise.

**Pull request closed without merging**
